language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36

before_install:
  - pip install -U setuptools;
    pip install tox;
          
script:
  - tox

notifications:
  email:
    - shuntingyard@gmail.com
