language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy

before_install:
  - pip install -U setuptools
    pip install tox
          
script:
  - tox

notifications:
  email:
    - shuntingyard@gmail.com
